import Navbar from "@/components/layout/Navbar";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const loggedUsernameCookie = (await cookies()).get("SocialUsername");
  return (
    <html lang="en" className={nunito.className}>
      <body>
        <Navbar loggedUsername={loggedUsernameCookie?.value} />
        {children}
      </body>
    </html>
  );
}
